name: practicum_project_3
channels:
  - bioconda
  - conda-forge
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - aragorn=1.2.41=h18d8cf3_5
  - argtable2=2.13=h10d778d_1004
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - barrnap=0.9=hdfd78af_4
  - bedtools=2.31.1=hbb299f0_3
  - blast=2.17.0=h53185c9_0
  - brotli=1.2.0=hb27157a_0
  - brotli-bin=1.2.0=h5c1846c_0
  - brotli-python=1.2.0=py314hd4d9bf7_0
  - bwa=0.7.19=h7f84b70_1
  - bzip2=1.0.8=h500dc9f_8
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py314h8ca4d5a_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - clustalo=1.2.4=h5eaf441_10
  - clustalw=2.1=h5fa12a8_12
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314h00ed6fe_3
  - cpython=3.14.0=py314hd8ed1ab_102
  - curl=8.17.0=h7dd4100_0
  - cycler=0.12.1=pyhcf101f3_2
  - debugpy=1.8.17=py314h93774dc_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrez-direct=24.0=h193322a_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h21dd04a_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - fontconfig=2.15.0=h37eeddb_1
  - fonttools=4.61.0=pyh7db6752_0
  - freetype=2.14.1=h694c41f_0
  - gawk=5.3.1=h0631170_0
  - gmp=6.3.0=hf036a51_2
  - gsl=2.7=h93259b0_0
  - h2=4.3.0=pyhcf101f3_0
  - hmmer=3.4=hc70aa7a_4
  - hpack=4.1.0=pyhd8ed1ab_0
  - htop=3.4.1=h79c18e1_0
  - htslib=1.22.1=h9f635df_0
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.14.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - igv=2.19.7=h33ea123_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - infernal=1.1.5=pl5321h5c2640d_4
  - ipykernel=7.1.0=pyh5552912_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kaleido-core=0.2.1=h0d85af4_0
  - kiwisolver=1.4.9=py314hf3ac25a_2
  - krb5=1.21.3=h37d8d59_0
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libasprintf=0.25.1=h3184127_1
  - libblas=3.9.0=38_he492b99_openblas
  - libbrotlicommon=1.2.0=h105ed1c_0
  - libbrotlidec=1.2.0=h660c9da_0
  - libbrotlienc=1.2.0=h2338291_0
  - libcblas=3.9.0=38_h9b27e0a_openblas
  - libcurl=8.17.0=h7dd4100_0
  - libcxx=21.1.5=h3d58e20_0
  - libdb=6.2.32=he49afe7_0
  - libdeflate=1.25=h517ebb2_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.5.2=h750e83c_0
  - libfreetype=2.14.1=h694c41f_0
  - libfreetype6=2.14.1=h6912278_0
  - libgettextpo=0.25.1=h3184127_1
  - libgfortran=15.2.0=h306097a_1
  - libgfortran5=15.2.0=h336fb69_1
  - libiconv=1.18=h57a12c2_2
  - libidn11=1.34=h112b980_0
  - libidn2=2.3.8=h13f126c_1
  - libintl=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.2=h8616949_0
  - liblapack=3.9.0=38_h859234e_openblas
  - liblzma=5.8.1=hd471939_2
  - libmpdec=4.0.0=h6e16a3a_0
  - libnghttp2=1.67.0=h3338091_0
  - libopenblas=0.3.30=openmp_h6006d49_3
  - libopenssl-static=3.6.0=h2fb6e4b_0
  - libpng=1.6.50=h84aeda2_1
  - libsodium=1.0.20=hfdf4475_0
  - libsqlite=3.51.0=h86bffb9_0
  - libssh2=1.11.1=hed3591d_0
  - libtiff=4.7.1=ha0a348c_1
  - libunistring=0.9.10=h0d85af4_0
  - libuuid=2.41.2=h9e50ec8_0
  - libwebp-base=1.6.0=hb807250_0
  - libxcb=1.17.0=hf1f96e2_0
  - libzlib=1.3.1=hd23fc13_2
  - littleutils=0.2.4=pyhd8ed1ab_1
  - llvm-openmp=21.1.5=h472b3d1_0
  - mafft=7.525=h2413b67_1
  - markdown=3.10=pyhcf101f3_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - mathjax=2.7.7=h694c41f_3
  - matplotlib=3.10.8=py314hee6578b_0
  - matplotlib-base=3.10.8=py314hd47142c_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minced=0.4.2=hdfd78af_1
  - mpfr=4.2.1=haed47dc_3
  - mpi=1.0=openmpi
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multiqc=1.32=pyhdfd78af_1
  - munkres=1.0.7=py_1
  - muscle=5.3=h8e8ab34_3
  - mysql-connector-c=6.1.11=h89ed7f3_1008
  - narwhals=2.11.0=pyhcf101f3_0
  - natsort=8.4.0=pyh29332c3_1
  - ncbi-vdb=3.3.0=h5fa12a8_0
  - ncurses=6.5=h0622a9a_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.4=py314hf08249b_0
  - openjdk=21.0.9=h2014cc5_0
  - openjpeg=2.5.4=h87e8dc5_0
  - openmpi=4.1.6=h7406208_101
  - openssl=3.6.0=h230baf5_0
  - outdated=0.2.2=pyhd8ed1ab_2
  - packaging=25.0=pyh29332c3_1
  - paml=4.10.7=h2413b67_1
  - pandas=2.3.3=py314hc4308db_1
  - pandas-flavor=0.8.1=pyhd8ed1ab_0
  - parallel=20251122=h694c41f_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.2=pyhcf101f3_0
  - pcre2=10.45=hf733adb_0
  - perl=5.32.1=7_h10d778d_perl5
  - perl-algorithm-diff=1.1903=pl5321hdfd78af_3
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321h6e16a3a_1
  - perl-base=2.23=pl5321hdfd78af_2
  - perl-bio-asn1-entrezgene=1.73=pl5321hdfd78af_3
  - perl-bio-coordinate=1.007001=pl5321hdfd78af_3
  - perl-bio-featureio=1.6.905=pl5321hdfd78af_4
  - perl-bio-samtools=1.43=pl5321h7f84b70_6
  - perl-bio-searchio-hmmer=1.7.3=pl5321hdfd78af_0
  - perl-bio-tools-phylo-paml=1.7.3=pl5321hdfd78af_3
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl5321hdfd78af_3
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl5321hdfd78af_5
  - perl-bioperl=1.7.8=hdfd78af_1
  - perl-bioperl-core=1.7.8=pl5321hdfd78af_1
  - perl-bioperl-run=1.007003=pl5321hdfd78af_0
  - perl-business-isbn=3.007=pl5321hdfd78af_0
  - perl-business-isbn-data=20210112.006=pl5321hdfd78af_0
  - perl-capture-tiny=0.48=pl5321hdfd78af_2
  - perl-carp=1.38=pl5321hdfd78af_4
  - perl-class-data-inheritable=0.09=pl5321hdfd78af_0
  - perl-clone=0.46=pl5321h1e3017b_0
  - perl-common-sense=3.75=pl5321hdfd78af_0
  - perl-compress-raw-bzip2=2.201=pl5321h9722bc1_0
  - perl-compress-raw-zlib=2.105=pl5321h9722bc1_0
  - perl-constant=1.33=pl5321hdfd78af_2
  - perl-data-dump=1.25=pl5321h18d8cf3_2
  - perl-data-dumper=2.183=pl5321ha5712d3_1
  - perl-db_file=1.858=pl5321h6e16a3a_0
  - perl-devel-stacktrace=2.04=pl5321hdfd78af_1
  - perl-digest-hmac=1.05=pl5321hdfd78af_0
  - perl-digest-md5=2.58=pl5321ha5712d3_1
  - perl-encode=3.19=pl5321ha5712d3_1
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-exception-class=1.45=pl5321hdfd78af_0
  - perl-exporter=5.72=pl5321hdfd78af_2
  - perl-exporter-tiny=1.002002=pl5321hdfd78af_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-listing=6.16=pl5321hdfd78af_0
  - perl-file-path=2.18=pl5321hd8ed1ab_0
  - perl-file-slurper=0.014=pl5321hdfd78af_0
  - perl-file-sort=1.01=pl5321hdfd78af_3
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-file-temp=0.2304=pl5321hd8ed1ab_0
  - perl-getopt-long=2.58=pl5321hdfd78af_0
  - perl-html-parser=3.81=pl5321hb3ea9af_0
  - perl-html-tagset=3.24=pl5321hdfd78af_0
  - perl-http-cookiejar-lwp=0.014=pl5321hdfd78af_0
  - perl-http-cookies=6.11=pl5321hdfd78af_0
  - perl-http-daemon=6.16=pl5321hdfd78af_0
  - perl-http-date=6.06=pl5321hdfd78af_0
  - perl-http-message=7.01=pl5321hdfd78af_0
  - perl-http-negotiate=6.01=pl5321hdfd78af_4
  - perl-inc-latest=0.500=pl5321h694c41f_0
  - perl-io-compress=2.201=pl5321h5eaf441_5
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-io-socket-ssl=2.074=pl5321hdfd78af_0
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-tty=1.16=pl5321ha5712d3_1
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-ipc-run=20250809.0=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h5fa12a8_0
  - perl-libwww-perl=6.81=pl5321hdfd78af_0
  - perl-libxml-perl=0.08=pl5321hdfd78af_3
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h18d8cf3_5
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-lwp-protocol-https=6.14=pl5321hdfd78af_1
  - perl-mime-base64=3.16=pl5321ha5712d3_2
  - perl-module-build=0.4234=pl5321h694c41f_1
  - perl-module-load=0.34=pl5321hdfd78af_0
  - perl-mozilla-ca=20250602=pl5321hdfd78af_0
  - perl-net-http=6.24=pl5321hdfd78af_0
  - perl-net-ssleay=1.94=pl5321h3dc7d44_1
  - perl-ntlm=1.09=pl5321hdfd78af_5
  - perl-parent=0.236=pl5321hdfd78af_2
  - perl-pathtools=3.75=pl5321ha5712d3_3
  - perl-scalar-list-utils=1.62=pl5321ha5712d3_0
  - perl-socket=2.027=pl5321h2413b67_6
  - perl-sub-uplevel=0.2800=pl5321ha5712d3_4
  - perl-test-deep=1.130=pl5321hdfd78af_0
  - perl-test-differences=0.69=pl5321hdfd78af_0
  - perl-test-exception=0.43=pl5321hdfd78af_3
  - perl-test-most=0.38=pl5321hdfd78af_0
  - perl-test-needs=0.002009=pl5321hdfd78af_0
  - perl-test-requiresinternet=0.05=pl5321hdfd78af_1
  - perl-test-warn=0.36=pl5321hdfd78af_2
  - perl-text-diff=1.45=pl5321hdfd78af_1
  - perl-time-local=1.35=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-tree-dag_node=1.35=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321hdfd78af_1
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-uri=5.12=pl5321hdfd78af_0
  - perl-url-encode=0.03=pl5321h527b516_1
  - perl-www-robotrules=6.02=pl5321hdfd78af_4
  - perl-xml-dom=1.46=pl5321hdfd78af_1
  - perl-xml-dom-xpath=0.14=pl5321hdfd78af_2
  - perl-xml-namespacesupport=1.12=pl5321hdfd78af_1
  - perl-xml-parser=2.44=pl5321h50c80e2_8
  - perl-xml-regexp=0.04=pl5321hdfd78af_3
  - perl-xml-sax=1.02=pl5321hdfd78af_1
  - perl-xml-sax-base=1.09=pl5321hdfd78af_1
  - perl-xml-sax-expat=0.51=pl5321hdfd78af_4
  - perl-xml-simple=2.25=pl5321hdfd78af_2
  - perl-xml-xpathengine=0.14=pl5321hdfd78af_3
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=12.0.0=py314h0a84944_0
  - pingouin=0.5.5=pyhd8ed1ab_1
  - pip=25.2=pyh145f28c_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - polars=1.35.1=pyh6a1acc5_0
  - polars-lts-cpu=1.34.0.deprecated=hc364b38_0
  - polars-runtime-32=1.35.1=py310hfb6bc98_0
  - polars-runtime-compat=1.35.1=py310h471337c_0
  - prodigal=2.6.3=h7f84b70_11
  - prokka=1.14.6=pl5321hdfd78af_5
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py314hd1e8ddb_0
  - pthread-stubs=0.4=h00291cd_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.4=pyh3cfb1c2_0
  - pydantic-core=2.41.5=py314ha7b6dee_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.14.0=hf88997e_102_cp314
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-gil=3.14.0=h4df99d1_102
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=pyh7db6752_0
  - pyzmq=27.1.0=py312hb7d603e_0
  - qhull=2020.2=h3c5361c_5
  - readline=8.2=h7cca4af_2
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py314h6482030_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.2.0=pyhcf101f3_0
  - rich-click=1.9.4=pyhd8ed1ab_0
  - rpds-py=0.28.0=py314ha7b6dee_2
  - samtools=0.1.19=ha21ef43_14
  - scikit-learn=1.7.2=py314h2ca3526_0
  - scipy=1.16.3=py314h9d854bd_1
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - seqkit=2.10.1=h193322a_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snpeff=5.3.0a=hdfd78af_1
  - snpsift=5.3.0a=hdfd78af_0
  - spades=4.2.0=hf6bce26_2
  - spectra=0.0.11=pyhd8ed1ab_2
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py314hd1ec8a2_1
  - t-coffee=12.00.7fb08c2=h26a2512_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbl2asn-forever=25.7.2f=h18d8cf3_6
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiktoken=0.12.0=py314h0484ab5_2
  - tk=8.6.13=hf689a15_2
  - tornado=6.5.2=py314h6482030_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trimmomatic=0.40=hdfd78af_0
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - ucsc-bigwigtobedgraph=482=h4328a2f_0
  - unicodedata2=17.0.0=py314h6482030_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - varscan=2.4.6=hdfd78af_0
  - viennarna=2.4.7=h470a237_4
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wget=1.25.0=hfb6e5ea_0
  - xarray=2025.11.0=pyhcf101f3_0
  - xorg-libxau=1.0.12=h8616949_1
  - xorg-libxdmcp=1.1.5=h8616949_1
  - yaml=0.2.5=h4132b18_3
  - zeromq=4.3.5=h6c33b1e_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hd23fc13_2
  - zlib-ng=2.2.5=h55e386d_0
  - zstandard=0.25.0=py314hd1e8ddb_1
  - zstd=1.5.7=h8210216_2
  - pip:
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bioframe==0.8.0
      - bleach==6.3.0
      - defusedxml==0.7.1
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - indexed-gzip==1.10.1
      - isoduration==20.11.0
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - lark==1.3.1
      - mistune==3.1.4
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - pandocfilters==1.5.1
      - prometheus-client==0.23.1
      - python-json-logger==4.0.0
      - quast==5.2.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - send2trash==1.8.3
      - simplejson==3.20.2
      - soupsieve==2.8
      - statannot==0.2.3
      - statannotations==0.7.2
      - terminado==0.18.1
      - tinycss2==1.4.0
      - uri-template==1.3.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
